### ISSUE TITLE
use 2 database mBass on a app

### ISSUE THREAD

**Issue by thanhhaiqtvn** [NIFTYCloud-mbaas/ncmb_android#107]
How to use 2 database mBass on a app android / iOS

**Comment by ncmbsdk** [comment]
@thanhhaiqtvn

Thank you for your reporting.
We are sorry, but if you have questions about how to use Nifty Cloud mobile backend,
please post in the following User Community.
https://github.com/NIFTYCloud-mbaas/UserCommunity
