### ISSUE TITLE
プッシュ通知アイコンの色を変更したい

### ISSUE THREAD

**Issue by sensp** [NIFTYCloud-mbaas/ncmb_android#108]
■環境
SDK v2.2.4 : 現在プッシュ通知のアイコン設定はあるげと、アイコン色を変更する設定がありません

■関連
Android 5.0 Lolipop以上で通知アイコンが白くなってしまう問題

■修正場所
①NCMB coreの改善
com.nifty.cloud.mb.core.NCMBGcmListenerService.java修正する
 static final String SMALL_ICON_COLOR = "smallIconColor";
：：：：：
  .setColor(appInfo.metaData.getInt(SMALL_ICON_COLOR))

②AndroidManifest.xmlのmeta-data定義設定からプッシュ通知アイコンの色を変更出来ます。
設定例：＜meta-data android:name="smallIconColor" android:value="0xff0000ff"/＞

**Comment by gs0zk1** [comment]
Mergeしたのでcloseします
