### ISSUE TITLE
NCMBRoleServiceのsetAclメソッドの名前変更

### ISSUE THREAD

**Issue by ykokw** [NIFTYCloud-mbaas/ncmb_android#115]
## 不具合の概要(Description of bug)

- SDKのバージョン(SDK version): v2.2.4
- 内容: NCMBRoleServiceのsetAcl / setAclInBackgroundメソッドが、roleのACL更新用にAPIをリクエストしているので、APIリクエストしていることが明確に分かるメソッド名に変更する

**Comment by vfa-datnh** [comment]
I was updated document SDK android
