### ISSUE TITLE
SDK初期化時のサンプルコード修正

### ISSUE THREAD

**Issue by ykokw** [NIFTYCloud-mbaas/ncmb_android#65]
NCMBクラスのinitializeにアプリケーションコンテキストを渡すように各サンプルコードを修正する

**Comment by gs0zk1** [comment]
下記のinitializeメソッド内のthisを
 NCMB.initialize(this, "applicationKey", "clientKey");
⇒ NCMB.initialize(this.getApplicationContext(), "applicationKey", "clientKey");
に変更
* example/PushTest
https://github.com/NIFTYCloud-mbaas/ncmb_android/blob/master/example/PushTest/app/src/main/java/com/nifty/cloud/mb/pushtest/MainActivity.java
* ドキュメントのサンプル・チュートリアル群
http://mb.cloud.nifty.com/doc/current/tutorial/tutorial_android.html

**Comment by gs0zk1** [comment]
https://github.com/NIFTYCloud-mbaas/ncmb_android/pull/121
