### ISSUE TITLE
signUp() has error when register first user. 

### ISSUE THREAD

**Issue by hocnguyen** [NIFTYCloud-mbaas/ncmb_android#91]
## 不具合の概要(Description of bug)
I downloaded the last version of ncmb_android.
When register first user, I get this error :  
> {"code":"E401001","error":"Authentication error by header incorrect."}

Then, I click again, it register success.
Sample code : 
> NCMBUser user = new NCMBUser();
 user.setUserName("TestUser1");
            user.setPassword("TestPassword");
            user.signUp();

**Comment by ykokw** [comment]
@hocnguyen 

Hi, I can't reproduce with following code

```java
package com.nifty.cloud.ncmb_test;

import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;
import android.util.Log;

import com.nifty.cloud.mb.core.NCMB;
import com.nifty.cloud.mb.core.NCMBException;
import com.nifty.cloud.mb.core.NCMBUser;

public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        NCMB.initialize(
                this.getApplicationContext(),
                "APPLICATION_KEY",
                "CLIENT_KEY"
        );
        NCMBUser user = new NCMBUser();
        user.setUserName("TestUser1");
        user.setPassword("TestPassword");
        try {
            user.signUp();
            Log.d("MAIN", user.getObjectId());
        } catch (NCMBException e) {
            Log.e("MAIN", e.getMessage());
        }
    }
}

```

I've executed in Android device, then I can confirm that user is registerd.
Is there anything other procedure for reproduce?

**Comment by sensp** [comment]
・成功しでも一応会員ClassをmBaasから全部削除します。
・新規Account処理をするとエラーになると思います。

**Comment by ykokw** [comment]
@sensp 

My procedure is here

- Delete All user from mobile backend in dashboard
- Uninstall the test app from android device
- Run the test app with above code

I can confirm that user is registerd.

**Comment by sensp** [comment]
・ソース参照をここから確認してみてください。
https://github.com/NIFTYCloud-mbaas/ncmb_android/tree/master/example/UserSample
・成功しでも一応会員ClassをmBaasから全部削除します。
・新規Account処理をするとエラーになると思います。

**Comment by sensp** [comment]
・ホークさんからの追加情報です。
case1)New Account -> insert user class -> mBaasから強制削除 -> New Account -> NG(E4010001)
case2)New Account -> insert user class -> AppからLogout -> mBaasから強制削除 -> New Account -> OK
case3)New Account -> insert user class -> Appから削除処理押す(user Classから削除される) -> New Account -> OK
※case1の場合ＮG(E4010001)が発生するみたいです。

**Comment by natsumo** [comment]
本件、APIの仕様のためCloseします。
