### ISSUE TITLE
parse data

### ISSUE THREAD

**Issue by thanhhaiqtvn** [NIFTYCloud-mbaas/ncmb_android#98]
Hello,

i created table "Test" on mBass.
I had got data from server.
my issues: how to parse NCMBObject to my object.
Thanks.

**Comment by ncmbsdk** [comment]
@thanhhaiqtvn 
Thank you for your reporting.
We are sorry, but if you have questions about how to use Nifty Cloud mobile backend, 
please post in the following User Community.
https://github.com/NIFTYCloud-mbaas/UserCommunity
